[2022-11-08T00:07:32.016+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate scheduled__2022-11-07T00:00:00+00:00 [queued]>
[2022-11-08T00:07:32.022+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate scheduled__2022-11-07T00:00:00+00:00 [queued]>
[2022-11-08T00:07:32.022+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-08T00:07:32.023+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-08T00:07:32.023+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-08T00:07:32.033+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): inaccurate> on 2022-11-07 00:00:00+00:00
[2022-11-08T00:07:32.036+0000] {standard_task_runner.py:55} INFO - Started process 25129 to run task
[2022-11-08T00:07:32.041+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'scheduled__2022-11-07T00:00:00+00:00', '--job-id', '173', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp9bwcs0he']
[2022-11-08T00:07:32.041+0000] {standard_task_runner.py:83} INFO - Job 173: Subtask inaccurate
[2022-11-08T00:07:32.085+0000] {task_command.py:376} INFO - Running <TaskInstance: my_dag.inaccurate scheduled__2022-11-07T00:00:00+00:00 [running]> on host 65bebd3e66a2
[2022-11-08T00:07:32.120+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2022-11-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-07T00:00:00+00:00
[2022-11-08T00:07:32.121+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-08T00:07:32.122+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "echo 'inaccurate'"]
[2022-11-08T00:07:32.130+0000] {subprocess.py:86} INFO - Output:
[2022-11-08T00:07:32.131+0000] {subprocess.py:93} INFO - inaccurate
[2022-11-08T00:07:32.132+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2022-11-08T00:07:32.145+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20221107T000000, start_date=20221108T000732, end_date=20221108T000732
[2022-11-08T00:07:32.170+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2022-11-08T00:07:32.180+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
